ALTER SESSION SET CURRENT_SCHEMA = VS_13_EQUIPE_6;

------------------------------------
-- CRIAÇÃO DA TABELA DE USUARIO
CREATE TABLE USUARIO (
	id NUMBER,
	nome VARCHAR2(80) NOT NULL,
	data_nascimento DATE NOT NULL,
	cpf CHAR(11) NOT NULL,
	email VARCHAR2(255),
	senha VARCHAR2(60) NOT NULL,
	acesso_pcd CHAR(1) NOT NULL CHECK (acesso_pcd IN ('S', 'N')),
	tipo_usuario NUMBER NOT NULL,
	interesses VARCHAR2(255),
	imagem_documento VARCHAR2(255),
	CONSTRAINT PK_USUARIO PRIMARY KEY(ID)
);

CREATE SEQUENCE SEQ_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

------------------------------------
-- CRIAÇÃO DA TABELA DE CLIENTE
CREATE TABLE CLIENTE (
	id NUMBER,
	id_usuario NUMBER,
	tipo_cliente NUMBER NOT NULL,
	tipo_plano NUMBER NOT NULL,
	controle_parental CHAR(1) NOT NULL CHECK (controle_parental IN ('S', 'N')),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID),
	CONSTRAINT PK_CLIENTE_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIO(id)
);

CREATE SEQUENCE SEQ_CLIENTE
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;


------------------------------------
-- CRIAÇÃO DA TABELA DE ESTUDANTE
CREATE TABLE ESTUDANTE (
	id NUMBER,
	id_cliente NUMBER,
	matricula VARCHAR2(10),							
	comprovante_matricula VARCHAR2(255),			
	instituicao VARCHAR2(255), 							
	curso VARCHAR2(255), 							
	data_inicio DATE, 								
	data_termino DATE, 								
	CONSTRAINT PK_ESTUDANTE PRIMARY KEY (ID),
	CONSTRAINT PK_ESTUDANTE_CLIENTE FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id)
);

CREATE SEQUENCE SEQ_ESTUDANTE
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;


------------------------------------
-- CRIAÇÃO DA TABELA DE PCD
CREATE TABLE PCD (
	id NUMBER,
	id_cliente NUMBER,
	tipo_deficiencia VARCHAR2(255),					
	certificado_deficiencia_gov VARCHAR2 (255),		
	CONSTRAINT PK_PCD PRIMARY KEY (ID),
	CONSTRAINT PK_PCD_CLIENTE FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id)
);

CREATE SEQUENCE SEQ_PCD
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;


------------------------------------
-- CRIAÇÃO DA TABELA DE PROFISSIONAL EM REALOCAÇÃO.
CREATE TABLE PROFISSIONAL_REALOCACAO (
	id NUMBER,
	id_cliente NUMBER,
	profissao VARCHAR2(255),						--PROFISSIONAL REALOCACAO
	objetivo_profissional VARCHAR2(255),				--PROFISSIONAL REALOCACAO
	CONSTRAINT PK_PROF_REALOC PRIMARY KEY (ID),
	CONSTRAINT PK_PROF_REALOC_CLIENTE FOREIGN KEY (id_cliente) REFERENCES CLIENTE(id)
);

CREATE SEQUENCE SEQ_PROFISSIONAL_REALOCACAO
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;


------------------------------------
-- CRIAÇÃO DE TABELA DE MENTORES
CREATE TABLE PROFISSIONAL_MENTOR (
    id NUMBER,
    id_usuario NUMBER NOT NULL,
    area_atuacao NUMBER NOT NULL,
    nivel_experiencia NUMBER NOT NULL,
    carteira_trabalho VARCHAR2(20) NOT NULL,
    documentos_validados CHAR(1) NOT NULL CHECK (documentos_validados IN ('S', 'N')),
    CONSTRAINT PK_PROFISSIONAL_MENTOR PRIMARY KEY (ID),
    CONSTRAINT PK_PROFISSIONAL_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIO(id)
);

CREATE SEQUENCE SEQ_PROFISSIONAL_MENTOR
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;


------------------------------------
-- CRIAÇÃO DE TABELA DE CERTIFICADOS
CREATE TABLE CERTIFICADO (
	id NUMBER,
	id_profissional_mentor NUMBER NOT NULL,
	CONSTRAINT PK_CERTIFICADO PRIMARY KEY (ID),
	CONSTRAINT FK_CERT_PROFISSIONAL_MENTOR FOREIGN KEY (id_profissional_mentor) REFERENCES PROFISSIONAL_MENTOR(id)
);

CREATE SEQUENCE SEQ_CERTIFICADO
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;


------------------------------------
-- CRIAÇÃO DE TABELA DE ENDERECOS
CREATE TABLE ENDERECO (
    id NUMBER NOT NULL,
    logradouro VARCHAR2(255) NOT NULL,
    numero VARCHAR2(5) NOT NULL,
    complemento VARCHAR2(255),
    cep VARCHAR2(8) NOT NULL,
    cidade VARCHAR2(255) NOT NULL,
    estado VARCHAR2(255) NOT NULL,
    pais VARCHAR2(255) NOT NULL,
    tipo NUMBER(1) NOT NULL,
    CONSTRAINT PK_ENDERECO PRIMARY KEY(id)
);

CREATE SEQUENCE SEQ_ENDERECO
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;


------------------------------------
-- CRIAÇÃO DE TABELA DE USUARIO_ENDERECO
CREATE TABLE USUARIO_ENDERECO (
	id_usuario NUMBER NOT NULL,
	id_endereco NUMBER NOT NULL,
	CONSTRAINT PK_USU_END PRIMARY KEY (id_usuario, id_endereco),
	CONSTRAINT FK_CLI_END_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIO(ID),
	CONSTRAINT FK_CLI_END_ENDERECO FOREIGN KEY (id_endereco) REFERENCES ENDERECO(ID)
);


------------------------------------
-- CRIACÃO DA TABELA CONTATO
CREATE TABLE CONTATO (
    id NUMBER NOT NULL,
    descricao VARCHAR2(255) NOT NULL,
    telefone VARCHAR2(13) NOT NULL,
    tipo NUMBER(1) NOT NULL,  
    CONSTRAINT PK_CONTATO PRIMARY KEY(id)
);

CREATE SEQUENCE SEQ_CONTATO	START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;



------------------------------------
--VINCULO DE CLIENTE COM CONTATO (DÁ DE FAZER TUDO NA CONTATO TB)
CREATE TABLE USUARIO_CONTATO (
	id_usuario NUMBER NOT NULL,
	id_contato NUMBER NOT NULL,
	CONSTRAINT PK_USU_CON PRIMARY KEY (id_usuario, id_contato),
	CONSTRAINT FK_CLI_CONT_USUARIO FOREIGN KEY (id_usuario) REFERENCES USUARIO(ID),
	CONSTRAINT FK_CLI_CONT_CONTATO FOREIGN KEY (id_contato) REFERENCES CONTATO(ID)
);

COMMIT;