ALTER SESSION SET CURRENT_SCHEMA = VS_13_EQUIPE_6;

DELETE FROM PCD;
DELETE FROM AGENDA;
DELETE FROM USUARIO;
DELETE FROM CONTATO;
DELETE FROM CLIENTE;
DELETE FROM ENDERECO;
DELETE FROM ESTUDANTE;
DELETE FROM USUARIO_CONTATO;
DELETE FROM USUARIO_ENDERECO;
DELETE FROM PROFISSIONAL_MENTOR;
DELETE FROM PROFISSIONAL_REALOCACAO;